import 'package:flutter/material.dart';

// ignore: camel_case_types
class appcolors {
  static Color primarycolor = Color(0xffDFFF6D);
  static Color navbaractive = Color(0xFFC7FF00);
  static Color buttoncoloronboarding = Color(0xff0B4B54);
  static Color pointcost = Color(0xFF0F3C46);
  static Color graytestonboard = Color(0xffB3B3B3);
  static Color graylinethrough = Color(0xff999999);
  static Color gradient1 = Color(0xFFE9FFBC); // light  green
  static Color producthiligt = Color(0xffF4FFCC);
  static Color producttext = Color(0xff789900);
  static Color gradient2 = Color(0xFFF9FFF9);
  static Color gradient3 = Color(0xffd8f4ee);
  static Color gradientauth1 = Color(0xFFD4F1F7);
 static Color reward = Color(0xff4D4D4D);
  static Color gradientauth2 = Color(0xFFE9FFBC);
  static Color textfieldborder = Color(0xffE6E6E6);
  static Color slider = Color(0xffCCCCCC);
  static Color gray700 = Color.fromARGB(201, 179, 179, 179);
  static Color grayviewall = Color(0xff999999).withOpacity(.8);
  static Color transcolor = Colors.transparent;
  static Color whicolor = Colors.white;
  static Color black = Colors.black;
  static Color black2 = Color(0xff282828);
  static Color card = Color(0XFF78E0ED);
  static Color carshilight = Color(0XFFF2F2F2);
  static Color green = Colors.green;
  static Color red = Colors.red;
  static const Color primary = Color(0xFF0D47A1);
  static const Color buttonColor = Color(0xFF003B4F); // Dark Teal
  static const Color headerGradientStart = Color(0xFFE0F7FA); // cyan[50]
  static const Color headerGradientEnd = Color(0xFFE3F2FD); // blue[50]
  static const Color textDark = Color(0xFF333333);
  static const Color borderGray = Color(0xFFEEEEEE);
  static const background = Color(0xFFF8F9FA);
  static const greenBadgeBg = Color(0xFFD4F4DD);
  static const greenBadgeText = Color(0xFF16A34A);
  static const yellowBadgeBg = Color(0xFFFEF3C7);
  static const yellowBadgeText = Color(0xFFCA8A04);
  static const textMain = Color(0xFF1F2937);
  static const borderColor = Color(0xFFE5E7EB);
  static const Color accent = Color(0xFF1E88E5);
  static const Color textBlack = Color(0xFF212121);
  static const Color textGrey = Color(0xFF757575);
  static const Color greenDiscount = Color(0xFFE8FAFC);
  static const Color klarnaPink = Color(0xFFFC568D);
  static const Color klarnaPinkpay = Color(0xffFEB4C7);
  static const Color lightBlue = Color(0xFFE3F2FD);
  static const Color darkGreen = Color(0xFF1B5E20);
  static const Color cardBackground = Color(0xFFf2f2f2);
  static const Color grey66 = Color(0xFF666666);
  static const secondary = Color(0xFF00A896);
  static const success = Color(0xFF4CAF50);
  static const textPrimary = Color(0xFF1A1A1A);
  static const textSecondary = Color(0xFF757575);
  static const border = Color(0xFFE0E0E0);
  static const discount = Color(0xFF4CAF50);
  static const buildpass = Color(0xFF555555);
  static const promocodeshare = Color(0xFFF9FFE5);
  static const promocodepoint = Color(0xFFE8FAFC);
  static const growthpoints = Color(0xff283300);
  static const accountbanner = Color(0xff06292D);
  static const deleteaccount = Color(0xffFF3838);
  static const tagTextColor = Color(0xff506600);
  static const klerna = Color(0xffB2FCE4);
  static const afterpay = Color(0xffD7FFEB);
  static const shippingoption = Color(0xff11A75C);
  static const categorytapbar = Color(0xFFD6D6D6);
    static const notificationcolor = Color(0xFFFFEBEE);
      static const divider = Color(0xFFF3F4F6);
        static const bottompartmanual = Color(0xFF0D7C66);
          static const pdsave = Color(0xFF0066CC);
}
